# -*- coding: utf-8 -*-
"""Prueba integral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVqOknn98UR-uXL8OUcfRHbTgllAnVV5
"""

pip install selenium webdriver-manager

"""**Login Exitoso**"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
import time

def setup_driver():
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
    driver.maximize_window()
    return driver

def test_login_exitoso():
    driver = setup_driver()
    driver.get("https://www.saucedemo.com/")

    driver.find_element(By.ID, "user-name").send_keys("standard_user")
    driver.find_element(By.ID, "password").send_keys("secret_sauce")
    driver.find_element(By.ID, "login-button").click()

    time.sleep(1)

    assert "inventory" in driver.current_url

    print("✔ Login exitoso validado")
    driver.quit()

"""**Login Fallido**"""

def test_login_fallido():
    driver = setup_driver()
    driver.get("https://www.saucedemo.com/")

    driver.find_element(By.ID, "user-name").send_keys("standard_user")
    driver.find_element(By.ID, "password").send_keys("wrongpass")
    driver.find_element(By.ID, "login-button").click()

    error = driver.find_element(By.CSS_SELECTOR, "h3[data-test='error']").text

    assert "Username and password do not match" in error

    print("✔ Login fallido validado")
    driver.quit()

"""**Validación campos obligatorios**"""

def test_campos_obligatorios():
    driver = setup_driver()
    driver.get("https://www.saucedemo.com/")

    driver.find_element(By.ID, "login-button").click()

    error = driver.find_element(By.CSS_SELECTOR, "h3[data-test='error']").text

    assert "Username is required" in error

    print("✔ Validación de campos obligatorios OK")
    driver.quit()

"""API"""

import requests

BASE_URL = "https://reqres.in/api"

def test_api_reqres():
    payload = {
        "name": "Test User",
        "job": "Automation Engineer"
    }

    response_post = requests.post(f"{BASE_URL}/users", json=payload)

    assert response_post.status_code == 201
    print("✔ POST 201 OK")

    data_post = response_post.json()
    user_id = data_post["id"]

    response_get = requests.get(f"{BASE_URL}/users/{user_id}")

    assert response_get.status_code == 200
    print("✔ GET 200 OK")